FROM balenalib/%%BALENA_ARCH%%-debian:bullseye AS build

RUN install_packages libtool libusb-1.0.0-dev librtlsdr-dev rtl-sdr doxygen git cmake gcc make
RUN git clone https://github.com/merbanan/rtl_433.git
COPY build.sh .

RUN chmod 766 build.sh
RUN ./build.sh

CMD rtl_433 -C si -F "mqtt://192.168.4.240:1883,user=mqttuser,pass=Bandit2022"


