FROM balenalib/%%BALENA_ARCH%%-debian:bullseye AS build

RUN install_packages libtool libusb-1.0.0-dev librtlsdr-dev rtl-sdr doxygen git cmake gcc make
RUN git clone https://github.com/merbanan/rtl_433.git
COPY build.sh .

RUN chmod +x build.sh
RUN ./build.sh

COPY run.sh /tmp/run.sh

RUN chmod +x /tmp/run.sh

CMD /tmp/run.sh

